### ISSUE TITLE
Script de migration custom pour les client 

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/ak#73]
### Context:

Après pas mal de test de marabunta, je trouve l’outils quelque peu limité. Point bloquant
obligation de mettre des numéro de version (qui n’ont pas de sens dans une PR)
complexité en cas de multi PR (gestion des conflicts)

### Bilan je propose quelque chose comme ça:

- un dossier migration
- un dossier par version
- un dossier qui s’appelle current

### Process:

Quand on fait une PR qui a besoin de migration on met des fichiers dans le dossier current.
- Les fichiers sont préfixé par pre-, post-, addons-
- Les fichiers (pre et post) peuvent être des commandes python, bash ou quoique ce soit qui est exécutable.
- Les fichiers addons- sont des fichiers texte qui contiendront la liste des addons à installer

Note : si on veut absolument jouer les pre- ou post- dans un ordre précis (car soucis suite au merge de plusieurs PR) il suffit de faire une PR qui met pre-1-, pre-2...

Dans l’image on a un script qui à partir des dossiers et fichier qui sont dans migration génère automatiquement le fichier de migration marabunta.

Je vais pinguer Guewen si il pense que c’est intéressant de mettre ça directement dans Marabunta (que marabunta support un fichier yaml ou découvert de fichier)

### Release d’une nouvelle version (ça sera dans AK)

Note pour les clients le numéro de version est la date du jours, ex: 20-05-01

Dans Ak on a la fonction release qui va mettre tout ce qui est dans current dans un dossier de release et pourquoi pas fusionner les fichiers addons- pour en faire qu’un seul.

**Comment by hparfr** [comment]
>Les fichiers addons- sont des fichiers texte qui contiendront la liste des addons à installer
`click-odoo-update` résoud cette problèmatique

**Comment by sebastienbeau** [comment]
Oui j'ai pas mal hésité a concerver ou pas la partie addons car effectivement click-odoo-update fait du bon boulot. Mais le seul problème qu'il a est que si tu fait une modif qui impact que le code python et donc pas de modification de modèle de donné alors tu vas faire un update pour rien et qui peut prendre du temps

**Comment by hparfr** [comment]
Je préfère partir sur click-odoo-update, mettre un KPI de temps de déploiement et analyser à postériori sur une longue période si on aurait eu un gain à faire différement.

**Comment by florian-dacosta** [comment]
Je ne connais pas trop click-odoo-update, mais si je comprends bien, c'est de la mise à jour auto de module si changement dans n'importe quel fichier de n'importe quel module?

On peut exclure des modules à ce système?
Autant pour tout ce qui est module natif, voir communautaire, ca ne me dérangerait pas tant, et le temps perdu devrait être acceptable pour la pluspart des projets.

Autant, cela me fait beaucoup plus peur en cas de petit patch sur un module natif (base, stock, sale...) ou même mise à jour. Souvent dans ces cas, c'est que du python qui change, et on a rarement envie de faire un update du module stock par exemple...qui pour le coup peut vraiment prendre du temps et pour un projet moyennement sain, peut potentiellement poser des soucis.

En dehors de cela, utiliser click-odoo semble pas mal...

Concernant la partie script de marabunta, ca me semble pas mal, mais j'ai un peu peur d'une perte de fonctionalité par rapport à l'existant.
Est-ce qu'on pourrait encore utiliser des options? On a par exemple l'option "install_command:" qui permet de mettre une commande différente de simplement "odoo" ce qui peut être utile dans certains contexte particuliers. je suppose qu'il y a d'autres options que je ne connais pas.

Plus important, dans le fichier migrate.yml, on peut indiquer un mode (demo, prod, ...)
C'est quelque chose qui est bien pratique, pour la CI notamment, même si on pourrait probablement faire différemment.
Marabunta fait probablement d'autre chose que je ne connais pas, et il serait relativement dommage de s'y couper.

**Comment by sebastienbeau** [comment]
@florian-dacosta, pour info j'ai vu avec Guewen et il partage un peu le même sentiment de limitation que l'on a. Je vais voir avec Ascone ce qu'il ont mais sinon l'idée serait de contribuer cette version dossier directement dans marabunta de base.

Pour le mode demo/prod au final je suis en train de totalement l'enlever car ça s'intègre mal avec le click-odoo-initdb et j'ai trouvé des astuces bien mieux pour lancer les tests. Mais je verrais avec Guewen ce qu'il en pense.

Bon en tout cas ça peut etre cool de passer par des dossiers

**Comment by sebastienbeau** [comment]
J'ai ouvert une issue sur marabunta https://github.com/camptocamp/marabunta/issues/54

**Comment by sebastienbeau** [comment]
@florian-dacosta après réflexion le truc que l'on pourrait faire c'est conserver le fichier migration.yaml (pour les options et le setup de demo) et le complété avec les informations du dossier

**Comment by bealdav** [comment]
Substitue le avec un toml, ahah ! Guewen sera pas contre

Au final quand tu vas agréger le contenu du dossier pour faire ton fichier de migration cela te fera un dico qui servira à la génération du fichier.

pip inclu déja la lib https://pypi.org/project/toml

le source pyYaml est de 270 kB que celui de toml est de 17kB

Moins de code, moins de pb de securité

**Comment by bealdav** [comment]
Je suis ok pour ma part pour la fusion dans un dossier current

**Comment by rvalyi** [comment]
Salut les gens, je dois encore réfléchir a la pertinence de la propostion. Mais sachez que je m'etais déjà pose la question de faire des update auto ou pas lors de deploy, des 2014 avec le git-deploy de Dokku a l’époque o super Seb faisais pas de devops... Et pour ça j'avais mis au point ce petit test en bash base sur diff:
modulesdiff: "
List of Odoo modules to update between current revision and a specified revision. First we get the list of modules for which we have a change in some XML data and then we complete with modules with database structure change in the Python files."
https://github.com/akretion/modulesdiff

Bon ça se base sur des heuristiques de savoir si on trouve des lignes avec fields. ou constraints dans les diff des fichiers py. **Il faudrait l'adapter de openerp a odoo...**. Ensuite ça extrait la liste de ces modules en liste séparée par des , dans le stdout (a passer direct dans le --update=). Je me dit que si on a quelques faux positifs ca perdrait un poil de temps mais pas autant que --update=all. Et si on ratait un module, ben on pourrait tj le forcer a la mano via une instruction de commit ou bon un fichier addons- comme le suggère Seb. Qu'en pensez vous?

A noter que pour ceux qui aiment pas le Bash, ca serait peut être possible en 50 lignes de Python aussi, via ce genre de module diff Python:
https://florian-dahlitz.de/blog/create-your-own-diff-tool-using-python
mais est-ce assez rapide pour odoo/odoo?

cc @sebastienbeau

**Comment by sebastienbeau** [comment]
This have been solved by using migrate
https://github.com/akretion/odoo-docker/blob/master/bin/migrate
