### ISSUE TITLE
Odoo and some plugin directory are too big

### ISSUE THREAD

**Issue by FranzPoize** [akretion/ak#94]
The git tree of big project are very heavy and odoo git tree takes more than 1GB just for the .git directory.

It would be nice to be able to use the depth option of git clone (https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) to avoid taking too much space.

Sparse does not resolve this issue because for some people (e.g. me in this case) I do not have enough space to download the repo in it's entirety.

Also an option to provide the possibility remove unused history from the git tree would be cool (see https://stackoverflow.com/a/34829535)

**Comment by hparfr** [comment]
you have to run `ak clone ` before ak build. it will init git folders with a partial clone.

https://github.com/akretion/ak/blob/master/ak/ak_clone.py#L62

**Comment by kevinkhao** [comment]
would there be any disadvantage to make ak clone && ak build the default for ak build ?

**Comment by hparfr** [comment]
back in the days, ak clone was based on new / experimental features of `git`; 

I plan to merge these commands in a next version of ak

**Comment by rvalyi** [comment]
also please consider merging that one as at least it avoids copying these gigantic clones in every Docky image we have on our computer:

https://github.com/akretion/docky-odoo-template/pull/91
